<a href="https://colab.research.google.com/github/varun82786/data-science-begning/blob/master/Introduction_to_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercise: 1

1. Create a NumPy array of the first five even numbers.

In [94]:
import numpy as np
arr =np.array([[1,2,3],[4,5,6],[7,8,9]])
arr
arr.size

9

In [95]:
ar=np.arange(10)
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [96]:
one=np.ones(9)
one

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [97]:
lin=np.linspace(start=1,stop=10,num=6)
lin

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

In [98]:
lin=np.linspace(start=17,stop=31,num=50)
lin

array([17.        , 17.28571429, 17.57142857, 17.85714286, 18.14285714,
       18.42857143, 18.71428571, 19.        , 19.28571429, 19.57142857,
       19.85714286, 20.14285714, 20.42857143, 20.71428571, 21.        ,
       21.28571429, 21.57142857, 21.85714286, 22.14285714, 22.42857143,
       22.71428571, 23.        , 23.28571429, 23.57142857, 23.85714286,
       24.14285714, 24.42857143, 24.71428571, 25.        , 25.28571429,
       25.57142857, 25.85714286, 26.14285714, 26.42857143, 26.71428571,
       27.        , 27.28571429, 27.57142857, 27.85714286, 28.14285714,
       28.42857143, 28.71428571, 29.        , 29.28571429, 29.57142857,
       29.85714286, 30.14285714, 30.42857143, 30.71428571, 31.        ])

In [99]:
np.append(ar,89)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 89])

In [100]:
np.reshape(arr,(9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [101]:
L = [10, 2, 7, 8, 3, 22, 54, 12, 13, 46, 23, 25, 41]
np.array(L)
l=np.sort(L)
np.delete(l,5)


array([ 2,  3,  7,  8, 10, 13, 22, 23, 25, 41, 46, 54])

In [102]:
e=np.arange(15)
d=np.reshape(e,(3,5))
print(d)
d[1:3,2:]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([[ 7,  8,  9],
       [12, 13, 14]])

In [103]:
arr=np.arange(25)
arr=arr.reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [104]:
arr=np.arange(25)
arr=arr.reshape(5,5)
arr[1:5:2,0:5:2]

array([[ 5,  7,  9],
       [15, 17, 19]])

In [105]:
# Create an 1d array from a list
import numpy as np
list1 = [0,1,2,3,4]
arr1d = np.array(list1)

# Print the array and its type
print(type(arr1d))
arr1d

<class 'numpy.ndarray'>


array([0, 1, 2, 3, 4])

In [106]:
arr1d+2

array([2, 3, 4, 5, 6])

In [107]:
list2 = [[0,1,2], [3,4,5], [6,7,8]]
arr2d=np.array(list2,dtype='float')
arr2d

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [108]:
arr2d.astype('int').astype('str')

array([['0', '1', '2'],
       ['3', '4', '5'],
       ['6', '7', '8']], dtype='<U21')

In [109]:
arr2d_b = np.array([1, 0,2], dtype='bool')
arr2d_b

array([ True, False,  True])

In [110]:
arr1d_obj=np.array([1,'a'],dtype='object')
arr1d_obj

array([1, 'a'], dtype=object)

In [111]:
arr1d_obj.tolist()

[1, 'a']

In [112]:
# Create a 2d array with 3 rows and 4 columns
list2 = [[1, 2, 3, 4],[3, 4, 5, 6], [5, 6, 7, 8]]
arr2 = np.array(list2, dtype='float')
arr2

array([[1., 2., 3., 4.],
       [3., 4., 5., 6.],
       [5., 6., 7., 8.]])

In [113]:
arr2.shape

(3, 4)

In [114]:
arr2.dtype

dtype('float64')

In [115]:
arr2.size

12

In [116]:
arr2.ndim

2

In [117]:
arr2

array([[1., 2., 3., 4.],
       [3., 4., 5., 6.],
       [5., 6., 7., 8.]])

In [118]:
arr2[:2,:2]

array([[1., 2.],
       [3., 4.]])

In [119]:
b=arr2>4
b

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [120]:
arr2[b]

array([5., 6., 5., 6., 7., 8.])

In [121]:
arr2[::-1,]

array([[5., 6., 7., 8.],
       [3., 4., 5., 6.],
       [1., 2., 3., 4.]])

In [122]:
arr2[::-1,::-1]

array([[8., 7., 6., 5.],
       [6., 5., 4., 3.],
       [4., 3., 2., 1.]])

In [123]:
arr2[1,1]=np.nan
arr2[1,2]=np.inf
arr2

array([[ 1.,  2.,  3.,  4.],
       [ 3., nan, inf,  6.],
       [ 5.,  6.,  7.,  8.]])

In [124]:
missing_bool=np.isnan(arr2)|np.isinf(arr2)
arr2[missing_bool]=-1
arr2

array([[ 1.,  2.,  3.,  4.],
       [ 3., -1., -1.,  6.],
       [ 5.,  6.,  7.,  8.]])

# `**How to compute mean, min, max on the ndarray?**`

In [125]:
arr2.mean()

3.5833333333333335

In [126]:
arr2.max()

8.0

In [127]:
# mean, max and min
print("Mean value is: ", arr2.mean())
print("Max value is: ", arr2.max())
print("Min value is: ", arr2.min())

Mean value is:  3.5833333333333335
Max value is:  8.0
Min value is:  -1.0


In [128]:
arr2

array([[ 1.,  2.,  3.,  4.],
       [ 3., -1., -1.,  6.],
       [ 5.,  6.,  7.,  8.]])

In [129]:
# Row wise and column wise min
print("Column wise minimum: ", np.amin(arr2, axis=0))
print("Row wise minimum: ", np.amin(arr2, axis=1))

Column wise minimum:  [ 1. -1. -1.  4.]
Row wise minimum:  [ 1. -1.  5.]


In [130]:
np.cumsum(arr2)

array([ 1.,  3.,  6., 10., 13., 12., 11., 17., 22., 28., 35., 43.])

In [131]:
arr2a = arr2[:2,:2]  
arr2a

array([[ 1.,  2.],
       [ 3., -1.]])

In [132]:
arr2a[:1,:1]=100
arr2a

array([[100.,   2.],
       [  3.,  -1.]])

In [133]:
arr2

array([[100.,   2.,   3.,   4.],
       [  3.,  -1.,  -1.,   6.],
       [  5.,   6.,   7.,   8.]])

In [134]:
arr2.reshape(4,3)

array([[100.,   2.,   3.],
       [  4.,   3.,  -1.],
       [ -1.,   6.,   5.],
       [  6.,   7.,   8.]])

In [135]:
arr2.flatten()

array([100.,   2.,   3.,   4.,   3.,  -1.,  -1.,   6.,   5.,   6.,   7.,
         8.])

In [136]:
b1=arr2.flatten()
b1[0]=12
b1

array([12.,  2.,  3.,  4.,  3., -1., -1.,  6.,  5.,  6.,  7.,  8.])

In [137]:
arr2

array([[100.,   2.,   3.,   4.],
       [  3.,  -1.,  -1.,   6.],
       [  5.,   6.,   7.,   8.]])

In [138]:
b2=arr2.ravel()
b2[0]=12
arr2

array([[12.,  2.,  3.,  4.],
       [ 3., -1., -1.,  6.],
       [ 5.,  6.,  7.,  8.]])

In [139]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [140]:
np.arange(1,8)

array([1, 2, 3, 4, 5, 6, 7])

In [142]:
np.arange(0,9,2)

array([0, 2, 4, 6, 8])

In [151]:
np.arange(10,0,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [153]:
np.linspace(start=1,stop=100,num=5,dtype='int')

array([  1,  25,  50,  75, 100])

In [163]:
# Limit the number of digits after the decimal to 2
np.set_printoptions(precision=2)  

# Start at 10^1 and end at 10^50
np.logspace(start=1, stop=50, num=10, base=10) 

array([1.00e+01, 2.78e+06, 7.74e+11, 2.15e+17, 5.99e+22, 1.67e+28,
       4.64e+33, 1.29e+39, 3.59e+44, 1.00e+50])

In [161]:
 

# Start at 10^1 and end at 10^50
np.logspace(start=1, stop=50, num=10, base=10) 

array([1.00e+01, 2.78e+06, 7.74e+11, 2.15e+17, 5.99e+22, 1.67e+28,
       4.64e+33, 1.29e+39, 3.59e+44, 1.00e+50])

In [164]:
a=[1,2,3,3,3]
np.tile(a,2)

array([1, 2, 3, 3, 3, 1, 2, 3, 3, 3])

In [166]:
np.repeat(a,9)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3])

In [167]:
hi

NameError: ignored